### ISSUE TITLE
C2146 & C4430 compile errors

### ISSUE THREAD

**Issue by nesa24** [adamhlt/D3D11-Hook-ImGui#1]
Imgui.h has errors 
C2146:sintax error missing ; before indentifier ImVec2
C4430:missing type specifier - int assumed

Any suggestions?

**Comment by adamhlt** [comment]
I'll look on my side if everything works and I'll get back to you

**Comment by adamhlt** [comment]
Everything works fine on my side, so I will close the issue because it's not related to my project but to ImGui.
